import './style/style.scss'
import './../blocks/engineering-works/engineering-works.scss'
import './../blocks/engineering-works/__content/engineering-works__content.scss'
import './../blocks/header/header.scss'
import './../blocks/footer/footer.scss'
import './../blocks/engineering-works/__content/engineering-works__content-timer'
import './../blocks/footer/__icons/footer__icons.scss'
import './../blocks/header/__description/header__description.scss'